### ISSUE TITLE
list of matrices

### ISSUE THREAD

**Issue by marcogenni** [UCA-MSI/dopa#1] opened 2020-11-02 12:39 UTC
I added a new test function in tests/tests_dopa.py (**test_consistency_np_array_2**), based on the new defined function **func5** at line 20 of the same file. Now, the weird thing is that the test succeds, but when calling dopa.parallelize on funct5,  **outside** of the unittest routine I have the following error:

  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)

TypeError: func5() takes 1 positional argument but 2 were given

You can reproduce  the error as follows: 

1. load the function **func5** in your Python environment,
2. define l = [np.ones((2,3)), np.ones((2,3)), np.ones((2,3)), np.ones((2,3))] and run
3. dopa.parallelize(l,func5)

**Comment by marcomilanesio** [comment] 2020-11-02 13:56
More info needed as I'm unable to reproduce the bug:
```
>>> import dopa
>>> import numpy as np
>>> arr = [np.ones((2,3)) for _ in range(10)]  # 10 matrices
>>> def func5(A):
...     return np.sum(A)
... 
>>> res = dopa.parallelize(arr, func5)
>>> res
[6.0, 6.0, 6.0, 6.0, 6.0, 6.0, 6.0, 6.0, 6.0, 6.0]
>>> 

```

Please: **DO NOT** modify the code on `master`

**Comment by marcogenni** [comment] 2020-11-02 15:35
Here the details of the error on Spyder:

runfile('/Users/marco/Documents/BoulotMSI/Appunti_Formazioni/dopa/tests/untitled0.py', wdir='/Users/marco/Documents/BoulotMSI/Appunti_Formazioni/dopa/tests')
Traceback (most recent call last):

  File "/Users/marco/Documents/BoulotMSI/Appunti_Formazioni/dopa/tests/untitled0.py", line 14, in <module>
    res = dopa.parallelize(arr, func5)

  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/dopa/dopa.py", line 116, in parallelize
    return do_parallel(runs, func, use_threads)

  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/dopa/dopa.py", line 97, in do_parallel
    result = future.result()

  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/_base.py", line 425, in result
    return self.__get_result()

  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception

  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)

TypeError: func5() takes 1 positional argument but 3 were given

**Comment by marcomilanesio** [comment] 2020-11-03 13:21
Looks like this has something to do with your `wdir`. Or the way the interpreter in Spyder is configured.
How did you installed `dopa`? Please paste the result of the following command:

```
python3 -c "import dopa; print(f'{dopa.__version__} - {dopa.__file__}')"
```

Also: check consistency between system interpreter and Spyder interpreter. Are they the same?

**Comment by marcogenni** [comment] 2020-11-03 14:05
Hi,  I used this line to install dopa:

pip install git+https://github.com/UCA-MSI/dopa.git

Here the  output of the command you suggested:

0.0.2 - /Users/marco/Documents/BoulotMSI/Appunti_Formazioni/dopa/dopa/__init__.py

**Comment by marcomilanesio** [comment] 2020-11-03 14:29
Looks like something went bad in the installation.
Problem n.1: output should be somewhere (depending on the location) ending with `dopa/__init__.py` (`init.py` is not a file)
For example, on a fresh new virtual env I have `0.0.2 - /home/marco/sw/temp/pack/lib/python3.8/site-packages/dopa/__init__.py`
Problem n.2: is ` /Users/marco/Documents/BoulotMSI/Appunti_Formazioni/dopa/dopa` in your `sys.path`?

Suggestion:
```
pip uninstall dopa
```
then, remove the source you cloned (`rm -rf /Users/marco/Documents/BoulotMSI/Appunti_Formazioni/dopa`)

then reinstall (`pip install git+https://github.com/UCA-MSI/dopa.git`)

**Comment by marcomilanesio** [comment] 2020-11-18 15:47
Any update? Closing this otherwise.

**Closed as completed** 2020-12-19 22:34 UTC
Labels: help wanted
